### ISSUE TITLE
Segfault when Start Core

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/Craft#7]
- Load Core --> Craft core
- Start Core
- Exit RetroArch
- Open RA again
- Choose Start Core, RA will segfault.

Linux 64 bits. Useless backtrace. RA crashes at first if you try Craft built with DEBUG=1

**Comment by orbea** [comment]
I am getting this too, with `DEBUG=1` craft will segmentation fault.
```
context_reset.
Mesa: User error: GL_INVALID_OPERATION in glUniform1(uniform "MVPMatrix"@0 is matrix)
Mesa: 6 similar GL_INVALID_OPERATION errors
Mesa: User error: GL_INVALID_OPERATION in glUniform1("ortho"@3 is int, not float)
Segmentation fault
```
The backtrace seems to be missing a lot of info as well.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe9b12eea in gen_water_buffer (x=-0.00177969504, y=11, z=-0.0042935391, 
    n=320) at src/main.c:451
451	}
(gdb) bt full
#0  0x00007fffe9b12eea in gen_water_buffer (x=-0.00177969504, y=11, 
    z=-0.0042935391, n=320) at src/main.c:451
        data = {-320.00177, 11, -320.004303, 0, 1, 0, 0.937988281, 0.999511719, 
          0, 0.5, 319.99823, 11, 319.995697, 0, 1, 0, 0.999511719, 0.937988281, 
          0, 0.5, 319.99823, 11, -320.004303, 0, 1, 0, 0.999511719, 0.999511719, 
          0, 0.5, -320.00177, 11, -320.004303, 0, 1, 0, 0.937988281, 
          0.999511719, 0, 0.5, -320.00177, 11, 319.995697, 0, 1, 0, 0.937988281, 
          0.937988281, 0, 0.5, 319.99823, 11, 319.995697, 0, -320.00177, 11, 
          -320.004303, 0, -1, 0, 0.937988281, 0.937988281, 0, 0.5, 319.99823, 
          11, 319.995697, 0, -1, 0, 0.999511719, 0.999511719, 0, 0.5, 
          -320.00177, 11, 319.995697, 0, -1, 0, 0.937988281, 0.999511719, 0, 
          0.5, -320.00177, 11, -320.004303, 0, -1, 0, 0.937988281, 0.937988281, 
          0, 0.5, 319.99823, 11, -320.004303, 0, -1, 0, 0.999511719, 
          0.937988281, 0, 0.5, 319.99823, 11, 319.995697, 0}
        ao = {{0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 
            0}, {0, 0, 0, 0}}
        light = {{0.5, 0.5, 0.5, 0.5}, {0.5, 0.5, 0.5, 0.5}, {0.5, 0.5, 0.5, 
            0.5}, {0.5, 0.5, 0.5, 0.5}, {0.5, 0.5, 0.5, 0.5}, {0.5, 0.5, 0.5, 
            0.5}}
#1  0x3f7fe0003f7fe000 in ?? ()
No symbol table info available.
#2  0x3f00000000000000 in ?? ()
No symbol table info available.
#3  0xbae944a8bb8cb0d1 in ?? ()
No symbol table info available.
#4  0x00007fffe9f19110 in model () from /usr/lib64/libretro/craft_libretro.so
No symbol table info available.
#5  0x00007fffe9f1d620 in info () from /usr/lib64/libretro/craft_libretro.so
No symbol table info available.
#6  0x3497b7283f96b095 in ?? ()
No symbol table info available.
#7  0xba2ad442ba2af0bd in ?? ()
No symbol table info available.
#8  0x3fc8eb73a896b097 in ?? ()
No symbol table info available.
#9  0x3990d79b3990efc1 in ?? ()
No symbol table info available.
#10 0x39e35b4eba491c6c in ?? ()
No symbol table info available.
#11 0xbf7ffffbbf801554 in ?? ()
No symbol table info available.
#12 0xbfc8eb643b0917dd in ?? ()
No symbol table info available.
#13 0xbb95c803be826230 in ?? ()
No symbol table info available.
#14 0x00007fffe9f1d620 in info () from /usr/lib64/libretro/craft_libretro.so
No symbol table info available.
#15 0x0000000000000001 in ?? ()
No symbol table info available.
#16 0x0000000000000000 in ?? ()
No symbol table info available.
```
With `DEBUG=0` craft will work, but is buggy (Character wont stop moving with a gamepad plugged in) and I will get a lot this, but these could be unrelated...
```
Mesa: User error: GL_INVALID_OPERATION in glUniform1(uniform "MVPMatrix"@0 is matrix)
Mesa: 6 similar GL_INVALID_OPERATION errors
Mesa: User error: GL_INVALID_OPERATION in glUniform1("ortho"@3 is int, not float)
Mesa: User error: GL_INVALID_OPERATION in glUniform1(uniform "MVPMatrix"@0 is matrix)
Mesa: 6 similar GL_INVALID_OPERATION errors
Mesa: User error: GL_INVALID_OPERATION in glUniform1("ortho"@3 is int, not float)
Mesa: User error: GL_INVALID_OPERATION in glUniform1(uniform "MVPMatrix"@0 is matrix)
Mesa: 6 similar GL_INVALID_OPERATION errors
Mesa: User error: GL_INVALID_OPERATION in glUniform1("ortho"@3 is int, not float)
Mesa: User error: GL_INVALID_OPERATION in glUniform1(uniform "MVPMatrix"@0 is matrix)
Mesa: 6 similar GL_INVALID_OPERATION errors
Mesa: User error: GL_INVALID_OPERATION in glUniform1("ortho"@3 is int, not float)
Mesa: User error: GL_INVALID_OPERATION in glUniform1(uniform "MVPMatrix"@0 is matrix)
Mesa: 6 similar GL_INVALID_OPERATION errors
```

**Comment by twinaphex** [comment]
Yeah like I said, it's a RetroArch MESA error, not a core one.

**Comment by orbea** [comment]
Sorry, that was not my intent. The segmentation fault is the same though?

**Comment by Fighter19** [comment]
Hey there I also have a crash at startup.
(ARM Android and Desktop)

The backtrace from my current version (using RA 1.4.1 stable)

```
#6  0x00007fffe4de1865 in vbo_draw_arrays () from /usr/lib64/dri/i965_dri.so
No symbol table info available.
#7  0x00007fffe402ced6 in render_sky.constprop.17 () from /usr/libexec/libretro/craft_libretro.so
No symbol table info available.
#8  0x00007fffe4031456 in main_run () from /usr/libexec/libretro/craft_libretro.so
No symbol table info available.
#9  0x00007fffe403606d in retro_run () from /usr/libexec/libretro/craft_libretro.so
No symbol table info available.
#10 0x0000000000415cf1 in core_run () at core_impl.c:437
No locals.
#11 0x0000000000426471 in runloop_iterate (sleep_ms=sleep_ms@entry=0x7fffffffdb40) at runloop.c:1156
        i = <optimized out>
        current = <optimized out>
        target = <optimized out>
        to_sleep_ms = <optimized out>
        trigger_input = 0
        last_input = 0
        input_driver_is_nonblock = false
        settings = 0x7ffff7e20010
        old_input = <optimized out>
        menu_is_alive = <optimized out>
        current_input = <optimized out>
---Type <return> to continue, or q <return> to quit---
#12 0x0000000000414c8a in rarch_main (argc=1, argv=<optimized out>, data=0x0) at frontend/frontend.c:130
        sleep_ms = 0
        ret = <optimized out>
        args = 0x0
```
